import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/providers/WagmiProvider";
import Navbar from "@/components/lottery/navbar";
import WalletProtectionProvider from "@/providers/WalletProtectionProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col bg-[#17121F] text-[#F4F0F7]">
        <Providers>
          <WalletProtectionProvider>
            <Navbar />
            <main className="flex-1">
              {children}
            </main>
          </WalletProtectionProvider>
        </Providers>
      </body>
    </html>
  );
}

